name: Create Release Tag

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4

    - name: Create and Push Tag
      run: |
        git tag ${{ steps.gitversion.outputs.majorMinorPatch }}
        git push origin ${{ steps.gitversion.outputs.majorMinorPatch }}
